---
- name: Setup mcfly
  hosts: localhost
  connection: local
  tasks:
    - name: verify latest Rust
      ansible.builtin.shell:
        cmd: |
          rustup update
    - name: Download/Install latest mcfly!
      ansible.builtin.shell:
        cmd: |
          cd $(mktemp -d)
          git clone https://github.com/cantino/mcfly
          cd mcfly
          cargo install --path .
