install:
	git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim || true
	nvim -c 'PackerInstall' 
clean:
	rm -rf ~/.cache/nvim
	rm -rf ~/.local/share/nvim
